lane :test do
  p = {
          :email => 'xxx@xx.com',
          :pwd => 'xxxxxxxx',
          :path => '/Users/xxx/Desktop/xxxx.ipa',
          :devices => [
          {
              "deviceid":'xxxxxxxx'
          }
          ],
          :project_name => 'xxxxx',
          :api_key => 'xxxxxx',
          :app_version => '6.4.0'
      }
  testin(email:p[:email],pwd:p[:pwd],path:p[:path],devices:p[:devices],project_name:p[:project_name],api_key:p[:api_key],app_version:p[:app_version])
end
