lane :test do
    p = {
        :email => 'xxx@xx.com',
        :pwd => 'xxxx',
        :path => '/Users/xxx/Desktop/xxx.ipa',
        :devices => [
        {
            "deviceid":'xxx'
        }
        ],
        :project_name => 'xxx',
        :api_key => 'xxxxxxxx',
        :app_version => '1.0.0'
        }
  testintask(email:p[:email],pwd:p[:pwd],path:p[:path],devices:p[:devices],project_name:p[:project_name],api_key:p[:api_key],app_version:p[:app_version])
end
